#!/usr/bin/env node
/**
 * generate-icons — rasterise `branding/icon.svg` into the seven assets `app/layout.tsx` and `app/manifest.ts`
 * declare (AC-1), **plus the two shell icons that live outside `web/`**: the Windows `.ico` and the iOS
 * `AppIcon`.
 *
 * WHY THIS IS COMMITTED
 * Before this script, all seven declared icons **404'd** — `public/` held only the untouched `create-next-app`
 * SVGs — so an installed app got a blank or generic home-screen tile. Generated binaries in a repo need a
 * reproducible path back to their source or nobody can safely change the logo, which is what this is.
 *
 * ONE AUTHORITY FOR THE MARK
 * The glyph is defined **once**, as the `id="mark"` path in `branding/icon.svg`. This script extracts that `d`
 * and composes each variant's own background and ink around it. Replace the master, re-run, commit — the
 * outputs cannot drift from the vector they came from.
 *
 * ⚠️ **It writes outside `web/`, deliberately.** The Windows shell's `app.ico` and the iOS `AppIcon` are the same
 * mark on the same plate as the web tile, and this script is where "the same mark" is enforced. The alternative
 * was two more hand-made copies of one logo — which is exactly what `mobile/android`'s `ic_launcher_foreground.xml`
 * already is (an Android vector cannot be generated by `sharp`, so it carries the path by hand *with a comment
 * naming this master*). Every output is written from `MARK`; nothing downstream re-draws it.
 *
 * ⚠️ It is Node + `sharp`, not Python + PIL, and that was forced rather than preferred: **PIL cannot read SVG**,
 * so a PIL script would have to hand-redraw the mark in drawing calls — a second authority for one logo. `sharp`
 * is already installed (Next's own dependency), so this adds nothing to `package.json`.
 *
 * DETERMINISM (plan R-9)
 * Generated binaries must not churn the diff on an unrelated re-run. Each SVG is emitted at its exact target
 * pixel size and rasterised at `density: 72`, so no resampling happens at all — the vector is rendered once, to
 * size. PNG options are pinned explicitly and no metadata is attached (`sharp` writes none unless asked). Two
 * runs on one machine produce byte-identical files; verify with `git diff --stat` after running.
 *
 *   node scripts/generate-icons.mjs
 */

import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import sharp from "sharp";

const WEB_ROOT = join(dirname(fileURLToPath(import.meta.url)), "..");
const REPO_ROOT = join(WEB_ROOT, "..");
const MASTER = join(WEB_ROOT, "branding", "icon.svg");
const OUT_DIR = join(WEB_ROOT, "public");
const DESKTOP_ASSETS = join(REPO_ROOT, "desktop", "ClinicManagement.DesktopShell", "Assets");
const IOS_APPICON = join(REPO_ROOT, "mobile", "ios", "ClinicShell", "Assets.xcassets", "AppIcon.appiconset");

/** The app's own tokens, converted from the oklch values in `app/globals.css`. */
const PRIMARY = "#00736b"; //   --primary            oklch(0.49 0.105 188)
const INK_ON_PRIMARY = "#f8fdfc"; // --primary-foreground oklch(0.99 0.005 190)

/**
 * Extract the glyph from the master.
 *
 * A throw, not a fallback: a silently-empty `d` would rasterise to a blank tile and the run would report success —
 * which is the failure this whole script exists to end.
 */
function readMarkPath() {
  const svg = readFileSync(MASTER, "utf8");
  const match = svg.match(/<path\b[^>]*\bid="mark"[^>]*\bd="([^"]+)"/);
  if (!match) {
    throw new Error(
      `generate-icons: no <path id="mark" d="…"> in ${MASTER}. The script composes every asset from that one ` +
        `path — see the comment at the top of the master.`,
    );
  }
  return match[1];
}

const MARK = readMarkPath();

/**
 * One variant's SVG, sized to its exact output pixels so nothing is resampled.
 *
 * `scale` is the glyph's size relative to the 512-unit master, applied about the centre. It is the only knob the
 * variants disagree on, and each disagreement is a platform rule stated at the call site below.
 */
function variantSvg({ size, background, radius, ink, scale }) {
  const offset = (512 * (1 - scale)) / 2;
  const plate =
    background === null
      ? ""
      : `<rect width="512" height="512" rx="${radius}" fill="${background}"/>`;
  return `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512" width="${size}" height="${size}">${plate}<g transform="translate(${offset} ${offset}) scale(${scale})"><path fill="${ink}" d="${MARK}"/></g></svg>`;
}

/**
 * The seven assets, each with the platform rule that fixes its shape.
 *
 * ⚠️ `scale`, `radius` and `flatten` are not styling choices — get one wrong and the tile is cropped, black, or
 * illegible on a device nobody develops on.
 */
const ASSETS = [
  {
    file: "icon-192.png",
    size: 192,
    background: PRIMARY,
    radius: 112,
    ink: INK_ON_PRIMARY,
    scale: 1,
    // The ordinary `purpose: "any"` tile: the app draws its own rounded plate, because "any" means the platform
    // will NOT mask it and a square of flat colour reads as an unfinished placeholder.
  },
  { file: "icon-512.png", size: 512, background: PRIMARY, radius: 112, ink: INK_ON_PRIMARY, scale: 1 },
  {
    file: "icon-maskable-512.png",
    size: 512,
    background: PRIMARY,
    radius: 0,
    ink: INK_ON_PRIMARY,
    scale: 0.78,
    /*
     * ⚠️ Maskable is the one asset with a hard geometric contract, and both halves of it matter.
     *
     *   • `radius: 0` — FULL BLEED. Android applies its own mask (circle, squircle, teardrop…), so a rounded
     *     plate here leaves transparent corners *outside* the mask and the tile gets a visible notch.
     *   • `scale: 0.78` — everything meaningful must sit inside the central circle of 80 % diameter (radius
     *     204.8 of 512), because that is all Android guarantees to keep. The mark's furthest point from centre
     *     is its top-left shoulder at (152, 128), i.e. 165 units, so at 0.78 it clears the safe circle with
     *     room rather than sitting on its edge.
     */
  },
  {
    file: "apple-icon.png",
    size: 180,
    background: PRIMARY,
    radius: 0,
    ink: INK_ON_PRIMARY,
    scale: 0.82,
    flatten: true,
    /*
     * ⚠️ 180 px, full bleed, and **no alpha**. iOS composites an apple-touch-icon over BLACK, so any
     * transparency — including the corners a rounded plate would leave — renders as black wedges around the
     * tile. iOS also rounds the icon itself, so `radius: 0` is right and the glyph is inset instead.
     */
  },
  {
    file: "icon-light-32x32.png",
    size: 32,
    background: null,
    radius: 0,
    ink: PRIMARY,
    scale: 1.18,
    /*
     * The favicons carry the mark ALONE on transparency, and slightly overscanned (`1.18`).
     *
     * A 32 px tab icon has ~26 px of usable glyph once a plate takes its margin, at which point the roots merge
     * into a blob. Dropping the plate and letting the mark bleed a little past the master's own bounds is what
     * keeps it readable at the one size where it is actually looked at.
     *
     * `light` = for a LIGHT browser chrome, so the ink is the primary. `layout.tsx` selects on
     * `prefers-color-scheme`.
     */
  },
  { file: "icon-dark-32x32.png", size: 32, background: null, radius: 0, ink: INK_ON_PRIMARY, scale: 1.18 },
];

/**
 * `/icon.svg` — the vector favicon, and the only asset that must answer both themes in ONE file.
 *
 * A browser picks a single SVG and then renders it under whatever chrome the user has, so the theme switch has to
 * live *inside* the document. `prefers-color-scheme` in an embedded stylesheet is the only mechanism for that;
 * the light ink is the default so a renderer that ignores the media query still shows something legible.
 */
function themedFaviconSvg() {
  const offset = (512 * (1 - 1.18)) / 2;
  return `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512" width="32" height="32">
  <style>
    .mark { fill: ${PRIMARY}; }
    @media (prefers-color-scheme: dark) { .mark { fill: ${INK_ON_PRIMARY}; } }
  </style>
  <g transform="translate(${offset} ${offset}) scale(1.18)"><path class="mark" d="${MARK}"/></g>
</svg>
`;
}

for (const asset of ASSETS) {
  let pipeline = sharp(Buffer.from(variantSvg(asset)), { density: 72 });
  // `flatten` before the PNG encode, so the alpha channel is gone from the file rather than merely opaque.
  if (asset.flatten) pipeline = pipeline.flatten({ background: asset.background });
  const buffer = await pipeline
    .png({ compressionLevel: 9, adaptiveFiltering: false, palette: false })
    .toBuffer();
  writeFileSync(join(OUT_DIR, asset.file), buffer);
  console.log(`  ✓ ${asset.file.padEnd(26)} ${asset.size}×${asset.size}`);
}

writeFileSync(join(OUT_DIR, "icon.svg"), themedFaviconSvg(), "utf8");
console.log(`  ✓ ${"icon.svg".padEnd(26)} vector, theme-aware`);

// ---- The two shell icons that live outside `web/` -------------------------------------------------

/**
 * Rasterise one square PNG of the standard plated tile.
 *
 * `scale` bumps slightly at the sizes where the glyph would otherwise be a few pixels across; it never exceeds
 * what the plate can hold, so nothing is clipped.
 */
function platedPng(size, { flatten = false } = {}) {
  const scale = size <= 32 ? 1.15 : 1;
  let pipeline = sharp(
    Buffer.from(
      variantSvg({
        size,
        background: PRIMARY,
        // The web tile's 112 of 512 (≈ 22 %), re-derived per size rather than hard-coded, so every output has
        // the same corner as the browser tab's.
        radius: Math.round((112 / 512) * size),
        ink: INK_ON_PRIMARY,
        scale,
      }),
    ),
    { density: 72 },
  );
  if (flatten) pipeline = pipeline.flatten({ background: PRIMARY });
  return pipeline.png({ compressionLevel: 9, adaptiveFiltering: false, palette: false }).toBuffer();
}

/**
 * Pack PNGs into a Windows `.ico`.
 *
 * ⚠️ Written here rather than pulled from a package: `sharp` cannot emit ICO, and the container is 6 header bytes
 * plus one 16-byte directory entry per image. A dependency for that is more supply chain than it is worth, and
 * `png-to-ico` would be the *second* thing in this repo that knows what the logo looks like.
 *
 * The payloads are PNG rather than DIB at every size. Windows has read PNG-compressed ICO entries since Vista and
 * the shell's target here is Windows 11; DIB would mean hand-writing a bottom-up BGRA bitmap plus its AND mask
 * for a platform that has not needed one in fifteen years.
 *
 * A height/width byte of **0 means 256** — the field is one byte and 256 does not fit in it. Getting that wrong
 * yields an icon Explorer silently skips rather than one it reports as broken.
 */
function packIco(images) {
  const header = Buffer.alloc(6);
  header.writeUInt16LE(0, 0); // reserved
  header.writeUInt16LE(1, 2); // type: 1 = icon
  header.writeUInt16LE(images.length, 4);

  const directory = Buffer.alloc(16 * images.length);
  let offset = header.length + directory.length;

  images.forEach(({ size, buffer }, i) => {
    const at = i * 16;
    directory.writeUInt8(size >= 256 ? 0 : size, at + 0); // width  (0 = 256)
    directory.writeUInt8(size >= 256 ? 0 : size, at + 1); // height (0 = 256)
    directory.writeUInt8(0, at + 2); // palette size: 0 = truecolour
    directory.writeUInt8(0, at + 3); // reserved
    directory.writeUInt16LE(1, at + 4); // colour planes
    directory.writeUInt16LE(32, at + 6); // bits per pixel
    directory.writeUInt32LE(buffer.length, at + 8);
    directory.writeUInt32LE(offset, at + 12);
    offset += buffer.length;
  });

  return Buffer.concat([header, directory, ...images.map((image) => image.buffer)]);
}

/**
 * The sizes Windows actually asks for: 16 (title bar, alt-tab list), 24/32 (taskbar, Explorer details), 48
 * (Explorer medium), 64/128/256 (large tiles, the installer's own icon, the Programs list at high DPI).
 * Omitting a size does not lose the icon — Windows rescales the nearest — but a downscaled 256 at 16 px is the
 * smeared tray icon everyone recognises as an unfinished app.
 */
const ICO_SIZES = [16, 24, 32, 48, 64, 128, 256];
const icoImages = [];
for (const size of ICO_SIZES) {
  icoImages.push({ size, buffer: await platedPng(size) });
}
mkdirSync(DESKTOP_ASSETS, { recursive: true });
writeFileSync(join(DESKTOP_ASSETS, "app.ico"), packIco(icoImages));
console.log(`  ✓ ${"desktop/…/Assets/app.ico".padEnd(26)} ${ICO_SIZES.join(", ")}`);

/**
 * iOS wants **one** 1024×1024 icon and composes every other size itself (single-size app icons, Xcode 14+).
 *
 * ⚠️ `flatten: true` for the same reason `apple-icon.png` carries it: iOS refuses an alpha channel in an app
 * icon outright — App Store Connect rejects the upload — and a locally-built one renders its transparent corners
 * black. `radius` is left to the platform: iOS applies its own superellipse mask, so a plate rounded here would
 * be rounded twice and show a light seam inside the corner.
 */
mkdirSync(IOS_APPICON, { recursive: true });
const appIcon = await sharp(
  Buffer.from(
    variantSvg({ size: 1024, background: PRIMARY, radius: 0, ink: INK_ON_PRIMARY, scale: 0.82 }),
  ),
  { density: 72 },
)
  .flatten({ background: PRIMARY })
  .png({ compressionLevel: 9, adaptiveFiltering: false, palette: false })
  .toBuffer();
writeFileSync(join(IOS_APPICON, "AppIcon-1024.png"), appIcon);
console.log(`  ✓ ${"mobile/ios/…/AppIcon-1024".padEnd(26)} 1024×1024, no alpha`);
