using System;
using System.Collections.Generic;
using System.Linq;
using System.Reflection;
using ClinicManagement.Domain.Common;
using ClinicManagement.Domain.Entities;
using Xunit;

namespace ClinicManagement.UnitTests.Common;

/// <summary>
/// <b>Every change to a patient's record reaches the journal.</b>
///
/// <para><b>Why this is a guard and not a code review.</b> <c>AuditSaveChangesInterceptor</c> decided what to
/// record by asking whether an entity derived from <c>AggregateRoot&lt;&gt;</c>, and that answered <b>no</b> for
/// the whole clinical record. Eight patient-owned types — the fiche de soins, every medical document, every
/// uploaded radiograph, the odontogramme, both histories, the patient flags and the payments — were plain
/// <c>Entity&lt;Guid&gt;</c> and produced <b>zero</b> audit rows on create, edit or delete. Deleting a patient's
/// prescriptions and x-rays left no trace and took the blobs with it. Editing a patient's <i>name</i> was
/// recorded; editing their <i>clinical notes</i> was not.</para>
///
/// <para>None of that was visible: the ledger was present, populated and correct about everything it did cover,
/// so « the journal works » was true and « the journal covers the medical record » was false at the same time.
/// A regulator, or a patient asking who changed their file, gets the same answer either way — nothing.</para>
///
/// <para><b>The requirement is derived from the model, not listed.</b> The rule is « carries a
/// <c>PatientId</c> ⇒ must be auditable », read off the entity types themselves, so the sixteenth patient-owned
/// entity is covered on the day it is written — the property an <c>[InlineData]</c> table of today's types
/// cannot have, because it can only fail on rows somebody remembered to add.</para>
/// </summary>
public class ClinicalRecordAuditCoverageTests
{
    /// <summary>
    /// Patient-owned types that deliberately do <b>not</b> belong in the clinical journal, with the reason.
    /// Asserted <b>equal in both directions</b>, so a stale entry fails as loudly as a new gap — the house
    /// style, and the half that stops an exemption outliving the code it was written for.
    /// </summary>
    private static readonly Dictionary<string, string> NotClinicalByDesign = new(StringComparer.Ordinal)
    {
        [nameof(Notification)] =
            "A staff feed row, not clinical content: it is *generated by* actions that are themselves audited "
            + "(an appointment booked, stock run low), so recording it would put a second, derivative row beside "
            + "every real one and bury the record it is meant to make readable.",
    };

    /// <summary>
    /// The rule: an entity that names a patient is part of that patient's record. Read off the CLR type, so it
    /// cannot drift from the model the way a hand-kept list would.
    /// </summary>
    private static bool CarriesAPatientId(Type type) =>
        type.GetProperty("PatientId", BindingFlags.Public | BindingFlags.Instance) is not null;

    private static bool IsAuditable(Type type)
    {
        if (typeof(IAuditable).IsAssignableFrom(type))
        {
            return true;
        }

        for (var candidate = type; candidate is not null; candidate = candidate.BaseType)
        {
            if (candidate.IsGenericType && candidate.GetGenericTypeDefinition() == typeof(AggregateRoot<>))
            {
                return true;
            }
        }

        return false;
    }

    private static IReadOnlyList<Type> PatientOwnedEntities() =>
        typeof(Patient).Assembly
            .GetTypes()
            .Where(t => t is { IsClass: true, IsAbstract: false })
            .Where(t => t.Namespace == typeof(Patient).Namespace)
            .Where(CarriesAPatientId)
            .OrderBy(t => t.Name, StringComparer.Ordinal)
            .ToList();

    [Fact]
    public void Every_Patient_Owned_Entity_Is_Auditable()
    {
        var unaudited = PatientOwnedEntities()
            .Where(t => !IsAuditable(t))
            .Select(t => t.Name)
            .OrderBy(n => n, StringComparer.Ordinal)
            .ToList();

        Assert.Equal(
            NotClinicalByDesign.Keys.OrderBy(k => k, StringComparer.Ordinal),
            unaudited);
    }

    /// <summary>
    /// Non-vacuity. A reflection scan fails <b>open</b>: a moved namespace or a renamed property would leave
    /// this class green for ever while checking nothing — how <c>SystemWideCallerCoverageTests</c>' console-verb
    /// branch matched nothing for two whole features.
    /// </summary>
    [Fact]
    public void The_Scan_Still_Sees_The_Clinical_Record()
    {
        var found = PatientOwnedEntities().Select(t => t.Name).ToList();

        Assert.True(found.Count >= 12, $"Only {found.Count} patient-owned entities found — the scan has drifted.");

        // The eight that were silently unaudited, named so a future refactor that stops covering one of them
        // fails here rather than in a regulator's question.
        foreach (var name in new[]
                 {
                     nameof(DentalRecord), nameof(MedicalDocument), nameof(PatientFile),
                     nameof(ToothState), nameof(PatientMedicalHistory), nameof(PatientFamilyHistory),
                     nameof(PatientFlag), nameof(Appointment),
                 })
        {
            Assert.Contains(name, found);
        }
    }

    /// <summary>
    /// <c>Payment</c> carries no <c>PatientId</c> — it hangs off the invoice — so the derived rule above cannot
    /// see it. It is money attached to a person's care and was equally unaudited, so it is asserted directly.
    /// </summary>
    [Fact]
    public void Payment_Is_Auditable_Even_Though_It_Names_No_Patient()
    {
        Assert.True(IsAuditable(typeof(Payment)));
    }
}
